import { useCheckpoints } from '../../services/checkpointApi';
import { useMemo } from 'react';

interface CheckpointDrawerProps {
  workflowId: string;
  onRestore: (checkpointId: string) => void;
}

export default function CheckpointDrawer({ workflowId, onRestore }: CheckpointDrawerProps) {
  const { 
    checkpoints: allCheckpoints, 
    stats,
    loading, 
    deleteCheckpoint, 
    restoreCheckpoint 
  } = useCheckpoints(workflowId);

  // Filter out auto-generated checkpoints - only show manual ones
  const manualCheckpoints = useMemo(() => {
    return allCheckpoints.filter(checkpoint => {
      // Show checkpoint if:
      // 1. No metadata/tags (legacy checkpoints)
      // 2. Has 'manual' tag
      // 3. Does NOT have 'auto-generated' tag
      const tags = checkpoint.metadata?.tags || [];
      const isAutoGenerated = tags.includes('auto-generated');
      const isManual = tags.includes('manual');
      
      // If it has tags, only show manual ones. If no tags, show it (legacy)
      return !isAutoGenerated && (isManual || tags.length === 0);
    });
  }, [allCheckpoints]);

  // Calculate manual checkpoint stats
  const manualStats = useMemo(() => {
    if (!stats) return null;
    
    return {
      ...stats,
      totalCheckpoints: manualCheckpoints.length,
      // Keep the latest checkpoint info from original stats since it might be needed for other features
    };
  }, [stats, manualCheckpoints.length]);

  const handleRestore = async (checkpointId: string) => {
    try {
      // Let the parent component handle the actual restore
      // Always call onRestore - parent handles the actual restoration
      onRestore(checkpointId);
      // Parent handles the restoration
    } catch (error) {
      console.error('Failed to restore checkpoint:', error);
    }
  };

  const handleDelete = async (checkpointId: string) => {
    if (window.confirm('Are you sure you want to delete this checkpoint?')) {
      await deleteCheckpoint(checkpointId);
    }
  };

  if (loading) return <div className="p-4 text-center text-gray-500">Loading checkpoints…</div>;

  return (
    <div className="p-4">
      {manualStats && (
        <div className="mb-4 text-sm text-gray-600 dark:text-gray-400 bg-gray-50 dark:bg-gray-700 p-3 rounded">
          <div className="font-medium mb-1">Manual Checkpoints</div>
          <div className="text-xs space-y-1">
            <div>Total: {manualStats.totalCheckpoints} saved checkpoints</div>
            {manualStats.totalCheckpoints > 0 && allCheckpoints.length > manualCheckpoints.length && (
              <div className="text-yellow-600 dark:text-yellow-400">
                ({allCheckpoints.length - manualCheckpoints.length} auto-checkpoints hidden)
              </div>
            )}
          </div>
        </div>
      )}
      
      {manualCheckpoints.length === 0 ? (
        <div className="text-center py-8 text-gray-500 dark:text-gray-400">
          <div className="text-sm">No manual checkpoints yet</div>
          <div className="text-xs mt-2">Create a checkpoint to save your current workflow state</div>
          {allCheckpoints.length > 0 && (
            <div className="text-xs mt-1 text-yellow-600 dark:text-yellow-400">
              ({allCheckpoints.length} auto-checkpoints are hidden)
            </div>
          )}
        </div>
      ) : (
        <div className="space-y-3">
          {manualCheckpoints.map(cp => (
            <div key={cp._id} className="border border-gray-200 dark:border-gray-600 rounded-lg p-3 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors">
              <div className="mb-2">
                <div className="font-medium text-gray-900 dark:text-white truncate">{cp.name}</div>
                {cp.description && (
                  <div className="text-xs text-gray-600 dark:text-gray-400 mt-1 line-clamp-2">{cp.description}</div>
                )}
              </div>
              
              <div className="flex items-center justify-between text-xs text-gray-500 dark:text-gray-400 mb-3">
                <div>{new Date(cp.createdAt).toLocaleDateString()}</div>
                <div>{cp.nodes.length}N • {cp.edges.length}E</div>
              </div>
              
              <div className="flex space-x-2">
                <button 
                  onClick={() => handleRestore(cp._id)} 
                  className="flex-1 px-3 py-1.5 text-xs bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
                >
                  Restore
                </button>
                <button 
                  onClick={() => handleDelete(cp._id)} 
                  className="px-3 py-1.5 text-xs border border-red-300 text-red-600 rounded hover:bg-red-50 dark:border-red-600 dark:text-red-400 dark:hover:bg-red-900/20 transition-colors"
                >
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
